import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { format } from 'date-fns';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '1 solid #333',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#666',
  },
  table: {
    marginTop: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    padding: 8,
    fontWeight: 'bold',
    borderBottom: '1 solid #333',
  },
  tableRow: {
    flexDirection: 'row',
    padding: 8,
    borderBottom: '1 solid #e0e0e0',
  },
  tableRowAlt: {
    flexDirection: 'row',
    padding: 8,
    backgroundColor: '#f9f9f9',
    borderBottom: '1 solid #e0e0e0',
  },
  col1: { width: '12%' },
  col2: { width: '20%' },
  col3: { width: '18%' },
  col4: { width: '15%' },
  col5: { width: '25%' },
  col6: { width: '10%', textAlign: 'right' },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#666',
    fontSize: 9,
    borderTop: '1 solid #e0e0e0',
    paddingTop: 10,
  },
  summary: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#f0f0f0',
  },
  summaryText: {
    fontSize: 11,
    marginBottom: 3,
  },
  summaryTotal: {
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: 5,
  },
});

interface Booking {
  id: number;
  date_time: string;
  first_name: string;
  last_name: string;
  email: string;
  address: string;
  postcode: string;
  total_cost: number;
  payment_status: string;
  booking_status: string;
  cleaners?: {
    first_name: string;
    last_name: string;
  } | null;
}

interface BookingsPDFProps {
  bookings: Booking[];
  title?: string;
}

export const BookingsPDF: React.FC<BookingsPDFProps> = ({ bookings, title = "Bookings Report" }) => {
  const totalCost = bookings.reduce((sum, booking) => {
    const cost = typeof booking.total_cost === 'string' ? parseFloat(booking.total_cost) : booking.total_cost;
    return sum + (cost || 0);
  }, 0);
  const paidCount = bookings.filter(b => b.payment_status === 'Paid' || b.payment_status === 'paid').length;
  const unpaidCount = bookings.filter(b => b.payment_status !== 'Paid' && b.payment_status !== 'paid').length;

  return (
    <Document>
      <Page size="A4" style={styles.page} orientation="landscape">
        <View style={styles.header}>
          <Text style={styles.title}>{title}</Text>
          <Text style={styles.subtitle}>
            Generated on {format(new Date(), 'dd MMM yyyy HH:mm')} • Total: {bookings.length} booking{bookings.length !== 1 ? 's' : ''}
          </Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.col1}>Date</Text>
            <Text style={styles.col2}>Customer</Text>
            <Text style={styles.col3}>Email</Text>
            <Text style={styles.col4}>Cleaner</Text>
            <Text style={styles.col5}>Address</Text>
            <Text style={styles.col6}>Total</Text>
          </View>

          {bookings.map((booking, index) => (
            <View key={booking.id} style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}>
              <Text style={styles.col1}>
                {format(new Date(booking.date_time), 'dd/MM/yyyy')}
              </Text>
              <Text style={styles.col2}>
                {booking.first_name} {booking.last_name}
              </Text>
              <Text style={styles.col3}>{booking.email || 'N/A'}</Text>
              <Text style={styles.col4}>
                {booking.cleaners 
                  ? `${booking.cleaners.first_name} ${booking.cleaners.last_name}`
                  : 'Unassigned'}
              </Text>
              <Text style={styles.col5}>
                {booking.address}, {booking.postcode}
              </Text>
              <Text style={styles.col6}>
                £{typeof booking.total_cost === 'string' 
                  ? parseFloat(booking.total_cost).toFixed(2) 
                  : (booking.total_cost?.toFixed(2) || '0.00')}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.summary}>
          <Text style={styles.summaryText}>Total Bookings: {bookings.length}</Text>
          <Text style={styles.summaryText}>Paid: {paidCount} • Unpaid: {unpaidCount}</Text>
          <Text style={styles.summaryTotal}>Total Revenue: £{totalCost.toFixed(2)}</Text>
        </View>

        <View style={styles.footer}>
          <Text>SN Cleaning Services • Generated by Admin Portal</Text>
        </View>
      </Page>
    </Document>
  );
};
