INSERT INTO public.bookings (
  customer,
  first_name,
  last_name,
  email,
  phone_number,
  address,
  postcode,
  service_type,
  cleaning_type,
  date_only,
  time_only,
  date_time,
  booking_status,
  payment_status,
  send_notification_email,
  created_by_source
) VALUES (
  414,
  'Audrey',
  'Whitfield',
  'xeiish@yahoo.com',
  '+447951131478',
  'Flat 21, London EC1R 5DQ, London',
  'EC1R 5DQ',
  'domestic',
  'regular',
  '2025-12-22',
  '09:00:00',
  '2025-12-22 09:00:00+00',
  'active',
  'Unpaid',
  false,
  'admin'
);