-- Phase 3.1: Recurring generation health — run history, admin RPCs, gap detection.
-- Cron "Create Recurring Bookings" already calls generate_recurring_bookings() every minute in production.

CREATE TABLE IF NOT EXISTS public.recurring_generation_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  status text NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error')),
  triggered_by text NOT NULL DEFAULT 'cron'
    CHECK (triggered_by IN ('cron', 'admin')),
  services_processed integer NOT NULL DEFAULT 0,
  bookings_created integer NOT NULL DEFAULT 0,
  bookings_skipped integer NOT NULL DEFAULT 0,
  services_with_errors integer NOT NULL DEFAULT 0,
  error_message text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS recurring_generation_runs_started_at_idx
  ON public.recurring_generation_runs (started_at DESC);

ALTER TABLE public.recurring_generation_runs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Staff can view recurring generation runs"
  ON public.recurring_generation_runs;
CREATE POLICY "Staff can view recurring generation runs"
  ON public.recurring_generation_runs
  FOR SELECT
  TO authenticated
  USING (
    public.has_role(auth.uid(), 'admin'::app_role)
    OR public.has_role(auth.uid(), 'sales_agent'::app_role)
  );

-- Drop prior void / overloaded signatures so RETURNS jsonb replaces cleanly
DROP FUNCTION IF EXISTS public.generate_recurring_bookings();
DROP FUNCTION IF EXISTS public.generate_recurring_bookings(text);

-- Enhanced generator: same booking logic, plus run logging / per-service errors / auto-resume.
CREATE OR REPLACE FUNCTION public.generate_recurring_bookings(
  p_triggered_by text DEFAULT 'cron'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rec RECORD;
  next_booking_date DATE;
  booking_datetime TIMESTAMP WITH TIME ZONE;
  booking_time TIME;
  address_text TEXT;
  address_postcode TEXT;
  service_hours NUMERIC;
  calculated_cleaner_pay NUMERIC;
  target_dow INTEGER;
  days_until_target INTEGER;
  base_date DATE;
  freq_interval INTERVAL;
  v_run_id bigint;
  v_services_processed integer := 0;
  v_bookings_created integer := 0;
  v_bookings_skipped integer := 0;
  v_services_with_errors integer := 0;
  v_errors jsonb := '[]'::jsonb;
  v_triggered_by text := COALESCE(NULLIF(trim(p_triggered_by), ''), 'cron');
  v_result jsonb;
BEGIN
  IF v_triggered_by NOT IN ('cron', 'admin') THEN
    v_triggered_by := 'cron';
  END IF;

  INSERT INTO public.recurring_generation_runs (triggered_by, status)
  VALUES (v_triggered_by, 'running')
  RETURNING id INTO v_run_id;

  -- Auto-resume postponed series when resume_date has arrived
  UPDATE public.recurring_services
  SET postponed = false,
      resume_date = NULL
  WHERE postponed IS TRUE
    AND resume_date IS NOT NULL
    AND resume_date::date <= CURRENT_DATE;

  BEGIN
    FOR rec IN
      SELECT
        rs.id,
        rs.customer,
        rs.cleaner,
        rs.address,
        rs.start_date,
        rs.start_time,
        rs.hours,
        rs.total_cost,
        rs.cost_per_hour,
        rs.cleaner_rate,
        rs.cleaning_type,
        rs.frequently,
        rs.days_of_the_week,
        rs.was_created_until,
        rs.recurring_group_id,
        rs.payment_method,
        c.first_name,
        c.last_name,
        c.email,
        c.phone
      FROM recurring_services rs
      LEFT JOIN customers c ON rs.customer = c.id
      WHERE rs.confirmed = true
        AND rs.postponed IS NOT TRUE
        AND rs.start_time IS NOT NULL
        AND rs.start_date IS NOT NULL
        AND rs.days_of_the_week IS NOT NULL
        AND rs.recurring_group_id IS NOT NULL
    LOOP
      BEGIN
        v_services_processed := v_services_processed + 1;

        CASE LOWER(REPLACE(rec.frequently, '-', ''))
          WHEN 'weekly' THEN freq_interval := INTERVAL '7 days';
          WHEN 'biweekly' THEN freq_interval := INTERVAL '14 days';
          WHEN 'monthly' THEN freq_interval := INTERVAL '30 days';
          ELSE freq_interval := INTERVAL '7 days';
        END CASE;

        target_dow := CASE LOWER(TRIM(SPLIT_PART(rec.days_of_the_week, ',', 1)))
          WHEN 'sunday' THEN 0
          WHEN 'monday' THEN 1
          WHEN 'tuesday' THEN 2
          WHEN 'wednesday' THEN 3
          WHEN 'thursday' THEN 4
          WHEN 'friday' THEN 5
          WHEN 'saturday' THEN 6
          ELSE NULL
        END;

        IF target_dow IS NULL THEN
          v_services_with_errors := v_services_with_errors + 1;
          v_errors := v_errors || jsonb_build_array(jsonb_build_object(
            'service_id', rec.id,
            'error', 'Invalid days_of_the_week'
          ));
          CONTINUE;
        END IF;

        IF rec.was_created_until IS NOT NULL THEN
          next_booking_date := rec.was_created_until + freq_interval;

          WHILE next_booking_date < CURRENT_DATE LOOP
            next_booking_date := next_booking_date + freq_interval;
          END LOOP;

          IF EXTRACT(DOW FROM next_booking_date)::INTEGER != target_dow THEN
            days_until_target := (target_dow - EXTRACT(DOW FROM next_booking_date)::INTEGER + 7) % 7;
            IF days_until_target = 0 THEN
              days_until_target := 7;
            END IF;
            next_booking_date := next_booking_date + days_until_target;
          END IF;
        ELSE
          base_date := GREATEST(rec.start_date::DATE, CURRENT_DATE);

          IF EXTRACT(DOW FROM base_date)::INTEGER = target_dow THEN
            next_booking_date := base_date;
          ELSE
            days_until_target := (target_dow - EXTRACT(DOW FROM base_date)::INTEGER + 7) % 7;
            IF days_until_target = 0 THEN
              days_until_target := 7;
            END IF;
            next_booking_date := base_date + days_until_target;
          END IF;
        END IF;

        service_hours := COALESCE(rec.hours::NUMERIC, 3);
        calculated_cleaner_pay := ROUND(service_hours * COALESCE(rec.cleaner_rate, 0), 2);

        SELECT a.address, a.postcode INTO address_text, address_postcode
        FROM addresses a WHERE a.id = rec.address::UUID;

        booking_time := rec.start_time::TIME;

        WHILE next_booking_date <= CURRENT_DATE + INTERVAL '30 days' LOOP
          booking_datetime := (next_booking_date || ' ' || booking_time)::TIMESTAMP WITH TIME ZONE;

          IF NOT EXISTS (
            SELECT 1 FROM bookings
            WHERE recurring_group_id = rec.recurring_group_id
              AND date_only = next_booking_date
          ) THEN
            INSERT INTO bookings (
              customer, cleaner, address, postcode, date_time, date_only, time_only,
              total_hours, total_cost, cleaning_type, frequently, booking_status,
              first_name, last_name, email, phone_number, recurring_group_id,
              cleaner_pay, cleaner_rate, payment_method, created_by_source
            ) VALUES (
              rec.customer, rec.cleaner, address_text, address_postcode, booking_datetime,
              next_booking_date, booking_time,
              service_hours, rec.total_cost, rec.cleaning_type, rec.frequently, 'upcoming',
              rec.first_name, rec.last_name, rec.email, rec.phone, rec.recurring_group_id,
              calculated_cleaner_pay, rec.cleaner_rate, rec.payment_method, 'recurring_auto'
            );
            v_bookings_created := v_bookings_created + 1;
          ELSE
            v_bookings_skipped := v_bookings_skipped + 1;
          END IF;

          UPDATE recurring_services SET was_created_until = next_booking_date WHERE id = rec.id;
          next_booking_date := next_booking_date + freq_interval;
        END LOOP;
      EXCEPTION WHEN OTHERS THEN
        v_services_with_errors := v_services_with_errors + 1;
        v_errors := v_errors || jsonb_build_array(jsonb_build_object(
          'service_id', rec.id,
          'error', SQLERRM
        ));
      END;
    END LOOP;

    UPDATE public.recurring_generation_runs
    SET finished_at = now(),
        status = 'success',
        services_processed = v_services_processed,
        bookings_created = v_bookings_created,
        bookings_skipped = v_bookings_skipped,
        services_with_errors = v_services_with_errors,
        details = jsonb_build_object('errors', v_errors)
    WHERE id = v_run_id;

  EXCEPTION WHEN OTHERS THEN
    UPDATE public.recurring_generation_runs
    SET finished_at = now(),
        status = 'error',
        services_processed = v_services_processed,
        bookings_created = v_bookings_created,
        bookings_skipped = v_bookings_skipped,
        services_with_errors = v_services_with_errors,
        error_message = SQLERRM,
        details = jsonb_build_object('errors', v_errors)
    WHERE id = v_run_id;
    RAISE;
  END;

  -- Keep run history bounded (cron runs every minute)
  DELETE FROM public.recurring_generation_runs
  WHERE started_at < now() - INTERVAL '7 days';

  v_result := jsonb_build_object(
    'run_id', v_run_id,
    'triggered_by', v_triggered_by,
    'services_processed', v_services_processed,
    'bookings_created', v_bookings_created,
    'bookings_skipped', v_bookings_skipped,
    'services_with_errors', v_services_with_errors,
    'errors', v_errors
  );
  RETURN v_result;
END;
$$;

-- Note: callers may use generate_recurring_bookings() with no args — DEFAULT 'cron' covers that.

CREATE OR REPLACE FUNCTION public.get_recurring_generation_health()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_last_run public.recurring_generation_runs%ROWTYPE;
  v_active integer;
  v_gaps jsonb;
  v_gap_count integer;
BEGIN
  IF NOT (
    public.has_role(auth.uid(), 'admin'::app_role)
    OR public.has_role(auth.uid(), 'sales_agent'::app_role)
  ) THEN
    RAISE EXCEPTION 'Staff access required';
  END IF;

  SELECT * INTO v_last_run
  FROM public.recurring_generation_runs
  ORDER BY started_at DESC
  LIMIT 1;

  SELECT count(*)::integer INTO v_active
  FROM public.recurring_services rs
  WHERE rs.confirmed = true
    AND rs.postponed IS NOT TRUE;

  SELECT coalesce(jsonb_agg(row_to_json(g)::jsonb ORDER BY g.service_id), '[]'::jsonb),
         count(*)::integer
  INTO v_gaps, v_gap_count
  FROM (
    SELECT
      rs.id AS service_id,
      trim(concat_ws(' ', c.first_name, c.last_name)) AS customer_name,
      rs.frequently,
      rs.days_of_the_week,
      rs.was_created_until,
      rs.start_time,
      CASE
        WHEN rs.start_time IS NULL OR rs.start_date IS NULL OR rs.days_of_the_week IS NULL
          THEN 'missing_schedule_fields'
        WHEN rs.recurring_group_id IS NULL
          THEN 'missing_group_id'
        WHEN NOT EXISTS (
          SELECT 1 FROM bookings b
          WHERE b.recurring_group_id = rs.recurring_group_id
            AND b.date_only >= CURRENT_DATE
            AND lower(coalesce(b.booking_status, '')) <> 'cancelled'
        ) THEN 'no_upcoming_booking'
        WHEN rs.was_created_until IS NULL OR rs.was_created_until < CURRENT_DATE + 14
          THEN 'horizon_lag'
        ELSE NULL
      END AS reason
    FROM public.recurring_services rs
    LEFT JOIN public.customers c ON c.id = rs.customer
    WHERE rs.confirmed = true
      AND rs.postponed IS NOT TRUE
  ) g
  WHERE g.reason IS NOT NULL;

  RETURN jsonb_build_object(
    'active_series', v_active,
    'gap_count', coalesce(v_gap_count, 0),
    'gaps', coalesce(v_gaps, '[]'::jsonb),
    'last_run', CASE
      WHEN v_last_run.id IS NULL THEN NULL
      ELSE jsonb_build_object(
        'id', v_last_run.id,
        'started_at', v_last_run.started_at,
        'finished_at', v_last_run.finished_at,
        'status', v_last_run.status,
        'triggered_by', v_last_run.triggered_by,
        'services_processed', v_last_run.services_processed,
        'bookings_created', v_last_run.bookings_created,
        'bookings_skipped', v_last_run.bookings_skipped,
        'services_with_errors', v_last_run.services_with_errors,
        'error_message', v_last_run.error_message
      )
    END
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.run_recurring_generation_now()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT (
    public.has_role(auth.uid(), 'admin'::app_role)
    OR public.has_role(auth.uid(), 'sales_agent'::app_role)
  ) THEN
    RAISE EXCEPTION 'Staff access required';
  END IF;

  RETURN public.generate_recurring_bookings('admin');
END;
$$;

GRANT SELECT ON public.recurring_generation_runs TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_recurring_bookings(text) TO postgres, service_role;
GRANT EXECUTE ON FUNCTION public.get_recurring_generation_health() TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_recurring_generation_now() TO authenticated;

-- Ensure cron job exists (idempotent). Production already has jobid 30 on * * * * *.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'Create Recurring Bookings') THEN
    PERFORM cron.schedule(
      'Create Recurring Bookings',
      '*/5 * * * *',
      $cmd$SELECT public.generate_recurring_bookings()$cmd$
    );
  END IF;
END $$;
